### ISSUE TITLE
간헐적인 위젯 찌그러짐

### ISSUE THREAD

**Issue by bekker** [wafflestudio/SNUTT-iOS#20]
![fb9d903a-9ad8-4f58-9d58-7dc8bbfa2e53](https://user-images.githubusercontent.com/4366401/38764507-5a851906-3feb-11e8-9646-68c44b6ba9f6.jpeg)

알 수 없는 원인에 의해 간헐적으로 발생

간략히 보기 눌렀다가 더보기 누르면 고쳐짐

**Comment by Rajin9601** [comment]
알고 있는 버그이지만 고치려면 widget api 의 정확한 동작을 알아야 될것 같음!
